# Generated by Django 3.0.8 on 2020-08-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainViews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
